<a href="https://colab.research.google.com/github/denizbaris/Data-with-Python/blob/main/DAwPython4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
data = [1,3,5,7,9]
data

[1, 3, 5, 7, 9]

In [ ]:
pd.DataFrame(data, columns=["col1"])

col1
0     1
1     3
2     5
3     7
4     9

In [ ]:
pd.Series(data)

0    1
1    3
2    5
3    7
4    9
dtype: int64

In [ ]:
data2 = np.arange(1,24,2).reshape(3,4)   
data2

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15],
       [17, 19, 21, 23]])

In [ ]:
df = pd.DataFrame(data2, columns=["col1","col2","col3","col4"], index = ["a","b","c"])
df

col1  col2  col3  col4
a     1     3     5     7
b     9    11    13    15
c    17    19    21    23

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
df.size

12

In [ ]:
df.shape

(3, 4)

In [ ]:
df.ndim  #shape icinde kac eleman varsa o kadar yani 2 boyutlu

2

In [ ]:
df.index


Index(['a', 'b', 'c'], dtype='object')

In [ ]:
df.columns

Index(['col1', 'col2', 'col3', 'col4'], dtype='object')

In [ ]:
df.values

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15],
       [17, 19, 21, 23]])

In [ ]:
df.keys()

Index(['col1', 'col2', 'col3', 'col4'], dtype='object')

In [ ]:
df.col1

a     1
b     9
c    17
Name: col1, dtype: int64

In [ ]:
df["col1"]

a     1
b     9
c    17
Name: col1, dtype: int64

In [26]:
s1 = np.random.randint(2,10, size = 40)
s2 = np.random.randint(30,100, size = 40)
s3 = np.random.randint(100,150, size = 40)
s1

array([9, 7, 6, 7, 9, 8, 9, 4, 2, 2, 4, 7, 3, 2, 8, 5, 2, 4, 5, 8, 7, 7,
       7, 2, 7, 4, 6, 4, 6, 6, 5, 5, 8, 8, 4, 6, 4, 5, 6, 2])

In [27]:
myDict = {'var1':s1, 'var2':s2, 'var3':s3}
myDict

{'var1': array([9, 7, 6, 7, 9, 8, 9, 4, 2, 2, 4, 7, 3, 2, 8, 5, 2, 4, 5, 8, 7, 7,
        7, 2, 7, 4, 6, 4, 6, 6, 5, 5, 8, 8, 4, 6, 4, 5, 6, 2]),
 'var2': array([71, 37, 72, 74, 58, 39, 33, 89, 69, 53, 76, 31, 91, 72, 38, 44, 43,
        48, 95, 75, 97, 65, 31, 44, 43, 82, 98, 89, 63, 84, 58, 34, 50, 91,
        66, 72, 64, 70, 49, 67]),
 'var3': array([144, 107, 104, 102, 140, 101, 101, 104, 117, 115, 120, 149, 124,
        124, 111, 103, 123, 109, 115, 134, 149, 110, 125, 118, 110, 110,
        123, 120, 145, 108, 142, 133, 117, 136, 148, 132, 140, 124, 105,
        135])}

In [29]:
df_dict = pd.DataFrame(myDict)
df_dict

var1  var2  var3
0      9    71   144
1      7    37   107
2      6    72   104
3      7    74   102
4      9    58   140
5      8    39   101
6      9    33   101
7      4    89   104
8      2    69   117
9      2    53   115
10     4    76   120
11     7    31   149
12     3    91   124
13     2    72   124
14     8    38   111
15     5    44   103
16     2    43   123
17     4    48   109
18     5    95   115
19     8    75   134
20     7    97   149
21     7    65   110
22     7    31   125
23     2    44   118
24     7    43   110
25     4    82   110
26     6    98   123
27     4    89   120
28     6    63   145
29     6    84   108
30     5    58   142
31     5    34   133
32     8    50   117
33     8    91   136
34     4    66   148
35     6    72   132
36     4    64   140
37     5    70   124
38     6    49   105
39     2    67   135

In [30]:
df_dict[3:5]

var1  var2  var3
3     7    74   102
4     9    58   140

In [31]:
df_dict2 = df_dict[3:5]
df_dict2

var1  var2  var3
3     7    74   102
4     9    58   140

In [32]:
df_dict2.index = ["a", "b"]
df_dict2

var1  var2  var3
a     7    74   102
b     9    58   140

In [33]:
df_dict2.columns = ["X","Y","Z"]
df_dict2

X   Y    Z
a  7  74  102
b  9  58  140

In [34]:
pd.DataFrame(df_dict2.values, index = ["c", "d"], columns=["t","r","s"])

t   r    s
c  7  74  102
d  9  58  140

### Indexing, selection and slicing  methods and several attributes using a different DataFrame

In [39]:
np.random.seed(101)
np.random.randn(5,4)

array([[ 2.70684984,  0.62813271,  0.90796945,  0.50382575],
       [ 0.65111795, -0.31931804, -0.84807698,  0.60596535],
       [-2.01816824,  0.74012206,  0.52881349, -0.58900053],
       [ 0.18869531, -0.75887206, -0.93323722,  0.95505651],
       [ 0.19079432,  1.97875732,  2.60596728,  0.68350889]])

In [55]:
df3 = pd.DataFrame(  np.random.randn(5,4),
                   index = ['A', 'B', 'C', 'D', 'E'],
                   columns = 'W X Y Z'.split())
df3

W         X         Y         Z
A -0.181904 -0.603235 -2.552660 -0.031927
B  1.407189  0.060971 -1.542393 -0.821110
C -1.599171 -2.068836  1.509747  0.174683
D  0.463428 -2.206442  0.544159  0.698296
E  1.252944 -1.048347 -1.281320  1.276731

In [56]:
'A B C D E'.split(" ")

['A', 'B', 'C', 'D', 'E']

In [58]:
df3["W"]

A   -0.181904
B    1.407189
C   -1.599171
D    0.463428
E    1.252944
Name: W, dtype: float64

In [59]:
df3[["W", "Y"]]

W         Y
A -0.181904 -2.552660
B  1.407189 -1.542393
C -1.599171  1.509747
D  0.463428  0.544159
E  1.252944 -1.281320

In [68]:
df3["W"] * df3["Y"]

A    0.464338
B   -2.170438
C   -2.414343
D    0.252178
E   -1.605422
dtype: float64

In [71]:
df3["Result"] = df3["W"]*df3["X"] + df3["Y"].std() - df3["Z"]
df3


W         X         Y         Z    Result
A -0.181904 -0.603235 -2.552660 -0.031927  1.792757
B  1.407189  0.060971 -1.542393 -0.821110  2.558007
C -1.599171 -2.068836  1.509747  0.174683  4.784839
D  0.463428 -2.206442  0.544159  0.698296 -0.069722
E  1.252944 -1.048347 -1.281320  1.276731 -0.939152

In [72]:
df3.drop("Result", axis = 1)   #df3.drop("Result", axis = 1, inplace=True)  inplace kalici degisiklik yapmak icin

W         X         Y         Z
A -0.181904 -0.603235 -2.552660 -0.031927
B  1.407189  0.060971 -1.542393 -0.821110
C -1.599171 -2.068836  1.509747  0.174683
D  0.463428 -2.206442  0.544159  0.698296
E  1.252944 -1.048347 -1.281320  1.276731

In [73]:
df3

W         X         Y         Z    Result
A -0.181904 -0.603235 -2.552660 -0.031927  1.792757
B  1.407189  0.060971 -1.542393 -0.821110  2.558007
C -1.599171 -2.068836  1.509747  0.174683  4.784839
D  0.463428 -2.206442  0.544159  0.698296 -0.069722
E  1.252944 -1.048347 -1.281320  1.276731 -0.939152

In [75]:
df3.drop(["Y","Result"], axis = 1, inplace=True)

In [76]:
df3

W         X         Z
A -0.181904 -0.603235 -0.031927
B  1.407189  0.060971 -0.821110
C -1.599171 -2.068836  0.174683
D  0.463428 -2.206442  0.698296
E  1.252944 -1.048347  1.276731

In [77]:
df3.drop(["C","E"], axis= 0, inplace=True)
df3

W         X         Z
A -0.181904 -0.603235 -0.031927
B  1.407189  0.060971 -0.821110
D  0.463428 -2.206442  0.698296

In [78]:
df3 = pd.DataFrame(  np.random.randn(5,4),
                   index = ['A', 'B', 'C', 'D', 'E'],
                   columns = 'W X Y Z'.split())
df3

W         X         Y         Z
A  0.645132 -0.297637  0.755742  1.758122
B  0.307046  0.529927  0.940120  0.746221
C -0.141266  0.085529 -1.883809 -1.314142
D  2.601240 -0.612552 -1.714963  1.350046
E  1.798990 -1.312854  0.033590 -0.220208

##allows us to select data using  index numbers of rows&columns. it is like classical indexing logic

In [79]:
m=np.random.randint(1,40, size=(8,4))
df4 = pd.DataFrame(m, columns = ["var1","var2","var3",'var4'])
df4

var1  var2  var3  var4
0    18    22    34    37
1    39    30    33     6
2    13    20    34    13
3    22    21    14    36
4     5    20    12    29
5    35    38    12    12
6    20    26    33    38
7    28    31    29    23

In [80]:
df4.loc[2]

var1    13
var2    20
var3    34
var4    13
Name: 2, dtype: int64

In [82]:
df4.loc[2:6]

var1  var2  var3  var4
2    13    20    34    13
3    22    21    14    36
4     5    20    12    29
5    35    38    12    12
6    20    26    33    38

In [83]:
df4.index='a b c d e f g h'.split()
df4

var1  var2  var3  var4
a    18    22    34    37
b    39    30    33     6
c    13    20    34    13
d    22    21    14    36
e     5    20    12    29
f    35    38    12    12
g    20    26    33    38
h    28    31    29    23

In [84]:
df4.loc["c"]

var1    13
var2    20
var3    34
var4    13
Name: c, dtype: int64

In [88]:
df4.loc["c":"f" , "var1":"var3"]

var1  var2  var3
c    13    20    34
d    22    21    14
e     5    20    12
f    35    38    12

In [89]:
df3.iloc[:,2:4]

Y         Z
A  0.755742  1.758122
B  0.940120  0.746221
C -1.883809 -1.314142
D -1.714963  1.350046
E  0.033590 -0.220208