<a href="https://colab.research.google.com/github/denizbaris/Data-with-Python/blob/main/DAwPython_Lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
my_list = [1,2,3,4,5,6,7,8]

In [4]:
a = np.array(my_list)
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [5]:
b = a[:3]
b

array([1, 2, 3])

In [6]:
b[0] = 88
b

array([88,  2,  3])

In [7]:
a

array([88,  2,  3,  4,  5,  6,  7,  8])

In [9]:
c = a.copy()
c[1] = 22
c

array([88, 22,  3,  4,  5,  6,  7,  8])

In [10]:
a

array([88,  2,  3,  4,  5,  6,  7,  8])

In [11]:
type(c)

numpy.ndarray

In [12]:
a.shape

(8,)

In [13]:
a[-1]

8

In [14]:
a[::-1]

array([ 8,  7,  6,  5,  4,  3,  2, 88])

In [15]:
b = np.array([[1,2,3], [6,7,8]])
b

array([[1, 2, 3],
       [6, 7, 8]])

In [16]:
b[1,1]=77
b

array([[ 1,  2,  3],
       [ 6, 77,  8]])

In [17]:
b[:,1]=99
b

array([[ 1, 99,  3],
       [ 6, 99,  8]])

In [19]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [20]:
np.full((3,3), 9)

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

In [26]:
np.empty((3,3), dtype=int)

array([[94151828059536,              0,              0],
       [94149978095616,              0,     8589934600],
       [             0,              0,              0]])

In [22]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [23]:
np.arange(5, 60, 3)

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50, 53,
       56, 59])

In [24]:
np.linspace(5, 60, 3)

array([ 5. , 32.5, 60. ])

In [25]:
np.linspace(2, 10, 5)

array([ 2.,  4.,  6.,  8., 10.])

In [27]:
np.random.rand(3,3)   

array([[0.13197182, 0.31283303, 0.82722477],
       [0.23917846, 0.7618124 , 0.37377202],
       [0.72399077, 0.28938464, 0.27417588]])

In [28]:
np.random.rand(3,3) #ortalamsi 0 varyansi 1 olacak sekilde degerler aliyor normal distribution olmasi icin

array([[0.44853954, 0.62069773, 0.93127187],
       [0.01690738, 0.08101626, 0.43460478],
       [0.24645128, 0.33189903, 0.83128244]])

In [29]:
np.random.randint(5,10, size =(3,3))

array([[7, 9, 6],
       [7, 8, 8],
       [8, 8, 8]])

In [30]:
z = np.random.randint(2,15, size = (5,3))
z

array([[ 7, 14,  9],
       [13, 14,  5],
       [ 2, 11, 13],
       [10,  9,  6],
       [11,  3, 13]])

In [31]:
z.shape

(5, 3)

In [34]:
z=z.reshape(3,5)
z

array([[ 7, 14,  9, 13, 14],
       [ 5,  2, 11, 13, 10],
       [ 9,  6, 11,  3, 13]])

In [36]:
z = z.ravel()
z

array([ 7, 14,  9, 13, 14,  5,  2, 11, 13, 10,  9,  6, 11,  3, 13])

In [37]:
z.max()

14

In [38]:
z.argmax()

1

In [39]:
my_arr = np.array([0,1,2,3,4,5,6,7,8,9]).reshape(5,2)

In [40]:
my_arr

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [41]:
my_arr_1 = np.array([3,4,5,6,7,8,9,10,11,12]).reshape(5,2)
my_arr_1

array([[ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [43]:
my_con = np.concatenate([my_arr,my_arr_1], axis = 1)  #axis 1 equal olunca sagina concatnate ediyor
my_con

array([[ 0,  1,  3,  4],
       [ 2,  3,  5,  6],
       [ 4,  5,  7,  8],
       [ 6,  7,  9, 10],
       [ 8,  9, 11, 12]])

In [44]:
my_con

array([[ 0,  1,  3,  4],
       [ 2,  3,  5,  6],
       [ 4,  5,  7,  8],
       [ 6,  7,  9, 10],
       [ 8,  9, 11, 12]])

In [45]:
my_con[1,[2,3]]

array([5, 6])

In [46]:
my_con[[3,1],2]

array([9, 5])

In [47]:
my_con[0:2,1:3]

array([[1, 3],
       [3, 5]])

In [48]:
my_con[:, [0,3]]

array([[ 0,  4],
       [ 2,  6],
       [ 4,  8],
       [ 6, 10],
       [ 8, 12]])

In [49]:
a = np.array([[1,2], [3,4]])
b = np.array([[5,6], [7,8]])

In [50]:
x = np.stack((a,b))
x

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [51]:
x.ndim

3

In [53]:
y = np.hstack((a,b))          #horizantal stack
y

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [54]:
y = np.vstack((a,b))            #vertical stack
y

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [57]:
array_1 = np.array([[1,2,3,4],
                    [5,6,7,8],
                    [9,10,11,12]])
array_1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [58]:
bigger_than_5=array_1>5
bigger_than_5

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [59]:
array_1[bigger_than_5]

array([ 6,  7,  8,  9, 10, 11, 12])

In [62]:
array_1[array_1<5]

array([1, 2, 3, 4])

In [63]:
array_1[(array_1<10) & (array_1>3)]

array([4, 5, 6, 7, 8, 9])

In [64]:
array_1[(array_1<10) | (array_1>3)]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [66]:
np.log(array_1)

array([[0.        , 0.69314718, 1.09861229, 1.38629436],
       [1.60943791, 1.79175947, 1.94591015, 2.07944154],
       [2.19722458, 2.30258509, 2.39789527, 2.48490665]])

In [67]:
np.exp(array_1)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03],
       [8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05]])

In [68]:
np.asfarray(array_1)

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [69]:
import pandas as pd


In [70]:
my_list = [1,2,3,4,5,6,7,8]
a=np.array(my_list)
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [71]:
pd.Series(my_list)

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
dtype: int64

In [72]:
labels = ['X','y','z', 'h']
my_list = [5, 10, 15, 20]
arr = np.array([25, 50, 75, 100])
d = {'a': 10, 'b': 20, 'c': 30, 'd':40}

In [73]:
pd.Series(my_list, index = labels)

X     5
y    10
z    15
h    20
dtype: int64

In [74]:
pd.Series(arr)

0     25
1     50
2     75
3    100
dtype: int64

In [75]:
pd.Series(d)

a    10
b    20
c    30
d    40
dtype: int64

In [76]:
ser = pd.Series([5,10,15,20,25,30], index = ['USA', 'Germany','France', 'UK','Turkey','Greece'])

In [77]:
ser.sort_values()

USA         5
Germany    10
France     15
UK         20
Turkey     25
Greece     30
dtype: int64

In [79]:
ser.sort_index()

France     15
Germany    10
Greece     30
Turkey     25
UK         20
USA         5
dtype: int64

In [83]:
'UK' in ser

True

In [85]:
ser.isin([25])

USA        False
Germany    False
France     False
UK         False
Turkey      True
Greece     False
dtype: bool

In [86]:
ser.keys()

Index(['USA', 'Germany', 'France', 'UK', 'Turkey', 'Greece'], dtype='object')

In [89]:
ser.items

<bound method Series.items of USA         5
Germany    10
France     15
UK         20
Turkey     25
Greece     30
dtype: int64>

In [91]:
for key, value in ser.items():
  print(key,value)

USA 5
Germany 10
France 15
UK 20
Turkey 25
Greece 30
