<a href="https://colab.research.google.com/github/denizbaris/Data-with-Python/blob/main/Numpy_Preclass.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
arr = np.arange(0,11)

In [2]:
import numpy as np
arr = np.arange(1,8)
arr[arr>4]

array([5, 6, 7])

In [3]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,50]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 50]])

In [4]:
arr_2d[0,2]

15

In [5]:
arr_1 = np.array([4,9,16,25,36])
arr_2 = np.array([2,3,4,5,6])
np.sqrt(arr_1)-np.max(arr_2)

array([-4., -3., -2., -1.,  0.])

In [6]:
arr_1 = np.array([5,6,7])
arr_2 = np.array([4,5,6])
arr_1-arr_2

array([1, 1, 1])

In [7]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,50]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 50]])

In [8]:
arr_2d[2,1]

40

In [9]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,50]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 50]])

In [11]:
arr_2d[:1,1:]

array([[10, 15]])

In [12]:
arr = np.arange(1,6)
arr[arr>3]

array([4, 5])

In [13]:
arr_1 = np.arange(0,10)
arr_2 = arr_1 * 3
np.max(arr_2)

27

In [14]:
arr_1 = np.array([4,9,16,25,36])
arr_2 = np.array([2,3,4,5,6])
np.sqrt(arr_1)-arr_2

array([0., 0., 0., 0., 0.])

In [15]:
arr=np.arange(1,37)
arr.shape

(36,)

In [16]:
import pandas as pd
people_dict={"first":["Richard", "Robert", "Jason"],
             "last" :["Stone", "Deepdive", "Seaborn"],
             "email": ["richardstone@email.com", "robertdeepdive@email.com", 
                        "jasonseaborn@email.com"]}
df=pd.DataFrame(people_dict)
df

first      last                     email
0  Richard     Stone    richardstone@email.com
1   Robert  Deepdive  robertdeepdive@email.com
2    Jason   Seaborn    jasonseaborn@email.com

In [17]:
df.iloc[2,1]

'Seaborn'

In [18]:
df.iloc[1,1]

'Deepdive'

In [19]:
df.iloc[2,2]

'jasonseaborn@email.com'

In [20]:
df.iloc[1,2]

'robertdeepdive@email.com'

In [21]:
outside = ['A1','A1','A1','A2','A2','A2']
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside,inside))
hier_index = pd.MultiIndex.from_tuples(hier_index)
np.random.seed(101)
data = pd.DataFrame(np.random.randn(6,2),index=hier_index,columns=['X','Y'])
data

X         Y
A1 1  2.706850  0.628133
   2  0.907969  0.503826
   3  0.651118 -0.319318
A2 1 -0.848077  0.605965
   2 -2.018168  0.740122
   3  0.528813 -0.589001

In [22]:
data.loc['A1', 'Y']

1    0.628133
2    0.503826
3   -0.319318
Name: Y, dtype: float64

In [23]:
data.loc['A1']

X         Y
1  2.706850  0.628133
2  0.907969  0.503826
3  0.651118 -0.319318

In [24]:
people_dict={"first":["Richard", "Robert", "Jason"],
             "last" :["Stone", "Deepdive", "Seaborn"],
             "email": ["richardstone@email.com", "robertdeepdive@email.com", 
                        "jasonseaborn@email.com"]}
df=pd.DataFrame(people_dict)
df

first      last                     email
0  Richard     Stone    richardstone@email.com
1   Robert  Deepdive  robertdeepdive@email.com
2    Jason   Seaborn    jasonseaborn@email.com

In [25]:
df["last"]

0       Stone
1    Deepdive
2     Seaborn
Name: last, dtype: object

In [26]:
data = pd.DataFrame({
    'age' :     [ 10, 22, 13, 21, 12, 11, 17],
    'section' : [ 'A', 'B', 'C', 'B', 'B', 'A', 'A'],
    'city' :    [ 'Gurgaon', 'Delhi', 'Mumbai', 'Delhi', 'Mumbai', 'Delhi', 'Mumbai'],
    'gender' :  [ 'M', 'F', 'F', 'M', 'M', 'M', 'F'],
    'favourite_color' : [ 'red', 'blue', 'yellow', 'pink', 'black', 'green', 'red']
})

data

age section     city gender favourite_color
0   10       A  Gurgaon      M             red
1   22       B    Delhi      F            blue
2   13       C   Mumbai      F          yellow
3   21       B    Delhi      M            pink
4   12       B   Mumbai      M           black
5   11       A    Delhi      M           green
6   17       A   Mumbai      F             red

In [27]:
data[['city','age']]

city  age
0  Gurgaon   10
1    Delhi   22
2   Mumbai   13
3    Delhi   21
4   Mumbai   12
5    Delhi   11
6   Mumbai   17

In [34]:
data.loc[B]

NameError: ignored

In [35]:
df = pd.DataFrame(np.arange(12).reshape(3, 4), columns=['A', 'B', 'C', 'D'])
df

A  B   C   D
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [36]:
people_dict={"first":["Richard", "Robert", "Jason"],
             "last" :["Stone", "Deepdive", "Seaborn"],
             "email": ["richardstone@email.com", "robertdeepdive@email.com", 
                        "jasonseaborn@email.com"]}
df=pd.DataFrame(people_dict)
df

first      last                     email
0  Richard     Stone    richardstone@email.com
1   Robert  Deepdive  robertdeepdive@email.com
2    Jason   Seaborn    jasonseaborn@email.com

In [37]:
df[(df['first']=="Richard") | (df['last'] == 'Deepdive')]

first      last                     email
0  Richard     Stone    richardstone@email.com
1   Robert  Deepdive  robertdeepdive@email.com

In [38]:
data[data["age"]>=21]

age section   city gender favourite_color
1   22       B  Delhi      F            blue
3   21       B  Delhi      M            pink

In [40]:
data['new'] = data['city'].str[:2]

In [41]:
data

age section     city gender favourite_color new
0   10       A  Gurgaon      M             red  Gu
1   22       B    Delhi      F            blue  De
2   13       C   Mumbai      F          yellow  Mu
3   21       B    Delhi      M            pink  De
4   12       B   Mumbai      M           black  Mu
5   11       A    Delhi      M           green  De
6   17       A   Mumbai      F             red  Mu

In [42]:
data.set_index('section', inplace=True)

In [43]:
data

age     city gender favourite_color new
section                                         
A         10  Gurgaon      M             red  Gu
B         22    Delhi      F            blue  De
C         13   Mumbai      F          yellow  Mu
B         21    Delhi      M            pink  De
B         12   Mumbai      M           black  Mu
A         11    Delhi      M           green  De
A         17   Mumbai      F             red  Mu

In [44]:
data.drop('city', axis=1, inplace=True)

In [45]:
data

age gender favourite_color new
section                                
A         10      M             red  Gu
B         22      F            blue  De
C         13      F          yellow  Mu
B         21      M            pink  De
B         12      M           black  Mu
A         11      M           green  De
A         17      F             red  Mu

In [52]:
data = pd.DataFrame({
    'age' :     [ 10, 22, 13, 21, 12, 11, 17],
    'section' : [ 'A', 'B', 'C', 'B', 'B', 'A', 'A'],
    'city' :    [ 'Gurgaon', 'Delhi', 'Mumbai', 'Delhi', 'Mumbai', 'Delhi', 'Mumbai'],
    'gender' :  [ 'M', 'F', 'F', 'M', 'M', 'M', 'F'],
    'favourite_color' : [ 'red', 'blue', 'yellow', 'pink', 'black', 'green', 'red']
})

data

age section     city gender favourite_color
0   10       A  Gurgaon      M             red
1   22       B    Delhi      F            blue
2   13       C   Mumbai      F          yellow
3   21       B    Delhi      M            pink
4   12       B   Mumbai      M           black
5   11       A    Delhi      M           green
6   17       A   Mumbai      F             red

In [47]:
data["city"]

0    Gurgaon
1      Delhi
2     Mumbai
3      Delhi
4     Mumbai
5      Delhi
6     Mumbai
Name: city, dtype: object

In [49]:
data.drop(6, axis=0, inplace=True)

In [50]:
data

age section     city gender favourite_color
0   10       A  Gurgaon      M             red
1   22       B    Delhi      F            blue
2   13       C   Mumbai      F          yellow
3   21       B    Delhi      M            pink
4   12       B   Mumbai      M           black
5   11       A    Delhi      M           green

In [54]:
data.iloc[2]

age                    13
section                 C
city               Mumbai
gender                  F
favourite_color    yellow
Name: 2, dtype: object

In [56]:
data.loc[['city','gender'], ['D','E']]


KeyError: ignored

In [60]:
data.iloc[[4,5], [2,3]]

city gender
4  Mumbai      M
5   Delhi      M

In [61]:
data.iloc[2:4, 2:3]

city
2  Mumbai
3   Delhi

In [62]:
data.iloc[3:4, 0:3]

age section   city
3   21       B  Delhi

In [63]:
data.iloc[3:5, 1:3]

section    city
3       B   Delhi
4       B  Mumbai

In [64]:
data.iloc[2:4, 2:3]

city
2  Mumbai
3   Delhi

In [65]:

data.drop(6, inplace=True)

In [66]:
data

age section     city gender favourite_color
0   10       A  Gurgaon      M             red
1   22       B    Delhi      F            blue
2   13       C   Mumbai      F          yellow
3   21       B    Delhi      M            pink
4   12       B   Mumbai      M           black
5   11       A    Delhi      M           green

In [67]:
data.iloc[1]

age                   22
section                B
city               Delhi
gender                 F
favourite_color     blue
Name: 1, dtype: object